### ISSUE TITLE
problem with Manifest.json

### ISSUE THREAD

**Issue by kvachakhia** [patrickzach/sage-mix#1]
`
Fatal error: Uncaught Roots\Acorn\Assets\Contracts\ManifestNotFoundException: The manifest [C:\laragon\www\david/wp-content/themes/david/public/manifest.json] cannot be found. in C:\laragon\www\david\wp-content\themes\david\vendor\roots\acorn\src\Roots\Acorn\Assets\Manager.php:133 Stack trace: #0 C:\laragon\www\david\wp-content\themes\david\vendor\roots\acorn\src\Roots\Acorn\Assets\Manager.php(101): Roots\Acorn\Assets\Manager->getJsonManifest('C:\\laragon\\www\\...') #1 C:\laragon\www\david\wp-content\themes\david\vendor\roots\acorn\src\Roots\Acorn\Assets\Manager.php(76): Roots\Acorn\Assets\Manager->resolve('theme', Array) #2 C:\laragon\www\david\wp-content\themes\david\vendor\roots\acorn\src\Roots\Acorn\Assets\AssetsServiceProvider.php(22): Roots\Acorn\Assets\Manager->manifest('theme') #3 C:\laragon\www\david\wp-content\themes\david\vendor\illuminate\container\Container.php(873): Roots\Acorn\Assets\AssetsServiceProvider->Roots\Acorn\Assets\{closure}(Object(Roots\Acorn\Application), Array) #4 C:\laragon\www\david\wp-conte in C:\laragon\www\david\wp-content\themes\david\vendor\roots\acorn\src\Roots\Acorn\Assets\Manager.php on line 133`

**Comment by patrickzach** [comment]
Looks like you have to create an empty manifests.json file in public/dist

I also just added the file to the repository
